version: "3"

dotenv:
  - .env

vars:
  ci:
    sh: "[[ -z $CI ]] && echo 0 || echo 1"

tasks:
  install: poetry install
  serve: uvicorn app:get_app --factory --reload

  migrate_generate: alembic revision --autogenerate
  migrate_apply: alembic upgrade head
  migrate_rollback: alembic downgrade -1

  test:
    summary: run tests
    desc: run tests
    env:
      NAMESPACE: museum-testing
      PYTHONPATH:
        sh: pwd
      MUSEUMFLAGS_FILE: flags.test.yml
    vars:
      parallel: '{{ if .parallel }} -n {{ .parallel }} {{ end }}'
      ignore_test: '{{ if .ignore_test }} -k "not ({{ .ignore_test }})" {{ end }}'
      specific_test: '{{ if .specific_test }} -k "({{ .specific_test }})" {{ end }}'
      without_coverage: '{{ if .without_coverage }} --no-cov {{ end }}'
      with_coverage: '{{ if not .without_coverage }} --cov-fail-under 80 --cov-report html:.cov_html --cov-report xml:coverage.xml --junit-xml tests/report_unit.xml {{ end }}'
    cmds:
      - |-
        poetry run pytest {{ default "tests/unit"  .filename }} -vvv --ff -x {{ .parallel }} -s \
        {{ .ignore_test }} {{ .specific_test }} \
        -W ignore::sqlalchemy.exc.SAWarning \
        --capture=no \
        {{ .without_coverage }} \
        {{ .with_coverage }} \
        {{.CLI_ARGS}}

  fmt:
    cmds:
      - task: isort
      - task: autoflake
      - task: black
  isort: isort .
  autoflake: autoflake -r --in-place --remove-duplicate-keys  --remove-all-unused-imports  --expand-star-imports --remove-unused-variables . > /dev/null
  black: black .
  isort-lint: isort --check .
  autoflake-lint: autoflake -r --in-place --remove-duplicate-keys  --remove-all-unused-imports  --expand-star-imports --remove-unused-variables --check .
  black-lint: black --check .
  lint:
    cmds:
      - task: isort-lint
      - task: autoflake-lint
      - task: black-lint