import { useRouter } from "expo-router";
import {
  Pressable,
  ScrollView,
  StyleSheet,
  Text,
  View,
} from "react-native";

const TITLE = "Terms of Service";

const BODY = `
Last updated: March 2025

Welcome to Artiou. By downloading, installing, or using the Artiou app ("App", "Service"), you agree to be bound by these Terms of Service ("Terms"). If you do not agree, do not use the App.

1. Description of the Service

Artiou is a museum guide application that allows you to:
• Take or upload photos of artworks and receive AI-generated descriptions and audio guides.
• Save favorites and, when logged in, sync them across your devices.
• Use text-to-speech to listen to artwork descriptions.

The Service is provided "as is" for personal, non-commercial use in museum and cultural settings.

2. Eligibility

You must be at least 13 years old (or the minimum age in your jurisdiction to consent to use of the Service) and have the legal capacity to enter into these Terms. By using the App, you represent that you meet these requirements.

3. Acceptable Use

You agree not to:
• Use the App for any illegal purpose or in violation of any law.
• Use the App to harass, abuse, or harm others, or to collect or share others’ personal information without consent.
• Attempt to reverse-engineer, decompile, or extract the source code of the App or our systems.
• Use automated means (bots, scrapers) to access the Service without our permission.
• Resell, sublicense, or commercially exploit the App or content generated by the App (e.g., descriptions, audio) except for your own personal use.
• Upload or submit content that infringes intellectual property, privacy, or other rights of any third party.

We may suspend or terminate your access if we reasonably believe you have violated these Terms.

4. Account and Sign-In

• You may use the App without an account for basic recognition and local collection. To sync your collection across devices, you can sign in with Apple.
• You are responsible for keeping your device and Apple account secure. Notify us if you suspect unauthorized access to your account.

5. AI-Generated Content and Accuracy

• Descriptions and audio guides are generated by artificial intelligence and may contain errors, omissions, or subjective interpretations. They are for general guidance only and do not replace expert advice or official museum information.
• We do not guarantee the accuracy, completeness, or suitability of any AI-generated content. You use such content at your own risk.

6. Intellectual Property

• The App, its design, branding, and our original content are owned by us or our licensors. You do not acquire any ownership by using the App.
• You retain ownership of photos you upload. By submitting a photo, you grant us a limited license to process it (e.g., send it to our AI and voice services) solely to provide the Service to you.
• AI-generated descriptions and audio are provided for your personal use; commercial use may require separate permission.

7. Privacy

Your use of the App is also governed by our Privacy Policy. By using the App, you consent to the collection and use of information as described in the Privacy Policy.

8. Disclaimers

TO THE MAXIMUM EXTENT PERMITTED BY LAW:
• THE SERVICE IS PROVIDED "AS IS" AND "AS AVAILABLE" WITHOUT WARRANTIES OF ANY KIND, EXPRESS OR IMPLIED.
• WE DISCLAIM ALL WARRANTIES, INCLUDING MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE, AND NON-INFRINGEMENT.
• WE DO NOT WARRANT THAT THE APP WILL BE UNINTERRUPTED, ERROR-FREE, OR FREE OF HARMFUL COMPONENTS.

9. Limitation of Liability

TO THE MAXIMUM EXTENT PERMITTED BY LAW:
• WE (AND OUR AFFILIATES, SUPPLIERS, AND LICENSORS) SHALL NOT BE LIABLE FOR ANY INDIRECT, INCIDENTAL, SPECIAL, CONSEQUENTIAL, OR PUNITIVE DAMAGES, OR FOR LOSS OF PROFITS, DATA, OR GOODWILL, ARISING FROM YOUR USE OF THE APP.
• OUR TOTAL LIABILITY FOR ANY CLAIMS ARISING OUT OF OR RELATED TO THESE TERMS OR THE APP SHALL NOT EXCEED THE AMOUNT YOU PAID US IN THE TWELVE (12) MONTHS BEFORE THE CLAIM (OR, IF YOU PAID NOTHING, ONE HUNDRED U.S. DOLLARS).

Some jurisdictions do not allow certain limitations; in such cases, the above limitations apply to you only to the extent permitted.

10. Indemnification

You agree to indemnify and hold harmless us and our officers, directors, employees, and agents from any claims, damages, losses, or expenses (including reasonable attorneys’ fees) arising from your use of the App, your violation of these Terms, or your violation of any third-party rights.

11. Changes to the Service and Terms

We may change the App or these Terms at any time. We will notify you of material changes to the Terms by posting the updated Terms in the App or by other reasonable means. Your continued use of the App after the effective date of the changes means you accept the new Terms. If you do not agree, you must stop using the App.

12. General

• Governing law: These Terms are governed by the laws of the jurisdiction in which we operate, without regard to conflict-of-law principles.
• Severability: If any part of these Terms is held invalid or unenforceable, the remaining parts will remain in effect.
• Entire agreement: These Terms (together with the Privacy Policy and any in-app rules) constitute the entire agreement between you and us regarding the App.
• No waiver: Our failure to enforce any right or provision of these Terms does not waive that right or provision.

13. Contact

For questions about these Terms of Service, please contact us at:
Email: legal@example.com
(Replace with your actual contact email or support URL.)
`.trim();

export default function TermsScreen() {
  const router = useRouter();

  return (
    <View style={styles.container}>
      <View style={styles.header}>
        <Pressable onPress={() => router.back()} style={styles.backBtn}>
          <Text style={styles.backText}>← Back</Text>
        </Pressable>
        <Text style={styles.title}>{TITLE}</Text>
      </View>
      <ScrollView
        style={styles.scroll}
        contentContainerStyle={styles.scrollContent}
        showsVerticalScrollIndicator={true}
      >
        <Text style={styles.body}>{BODY}</Text>
      </ScrollView>
    </View>
  );
}

const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: "#F6E7D7",
  },
  header: {
    flexDirection: "row",
    alignItems: "center",
    paddingHorizontal: 16,
    paddingTop: 56,
    paddingBottom: 12,
    borderBottomWidth: 1,
    borderBottomColor: "#E2461B",
  },
  backBtn: {
    marginRight: 12,
    paddingVertical: 8,
    paddingRight: 8,
  },
  backText: {
    fontSize: 16,
    color: "#E2461B",
    fontWeight: "700",
  },
  title: {
    fontSize: 20,
    fontWeight: "800",
    color: "#E2461B",
  },
  scroll: {
    flex: 1,
  },
  scrollContent: {
    padding: 20,
    paddingBottom: 40,
  },
  body: {
    fontSize: 14,
    lineHeight: 22,
    color: "#4B3621",
  },
});
