"""empty message

Revision ID: 435a7593c186
Revises: 703ea995db4b
Create Date: 2026-03-10 18:02:21.705264

"""

import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from alembic import op

# revision identifiers, used by Alembic.
revision = "435a7593c186"
down_revision = "703ea995db4b"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "scan_record",
        sa.Column(
            "inserted_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "scan_id",
            postgresql.UUID(),
            server_default=sa.text("uuid_generate_v4()"),
            nullable=False,
        ),
        sa.Column("user_id", postgresql.UUID(), nullable=True),
        sa.Column("artwork_code", sa.String(), nullable=True),
        sa.Column("image_path", sa.String(), nullable=False),
        sa.Column("text", sa.String(), nullable=False),
        sa.Column("audio_path", sa.String(), nullable=True),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["museum_sources.user.user_id"],
            onupdate="CASCADE",
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("scan_id"),
        sa.UniqueConstraint("scan_id"),
        schema="museum_sources",
    )
    op.create_index(
        op.f("ix_museum_sources_scan_record_user_id"),
        "scan_record",
        ["user_id"],
        unique=False,
        schema="museum_sources",
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        op.f("ix_museum_sources_scan_record_user_id"),
        table_name="scan_record",
        schema="museum_sources",
    )
    op.drop_table("scan_record", schema="museum_sources")
    # ### end Alembic commands ###
