"""empty message

Revision ID: aca07de10580
Revises: 435a7593c186
Create Date: 2026-03-10 21:20:19.720518

"""

import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from alembic import op

# revision identifiers, used by Alembic.
revision = "aca07de10580"
down_revision = "435a7593c186"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "favorite_scan",
        sa.Column(
            "inserted_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "favorite_scan_id",
            postgresql.UUID(),
            server_default=sa.text("uuid_generate_v4()"),
            nullable=False,
        ),
        sa.Column("user_id", postgresql.UUID(), nullable=False),
        sa.Column("scan_id", postgresql.UUID(), nullable=False),
        sa.ForeignKeyConstraint(
            ["scan_id"],
            ["museum_sources.scan_record.scan_id"],
            onupdate="CASCADE",
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["museum_sources.user.user_id"],
            onupdate="CASCADE",
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("favorite_scan_id"),
        sa.UniqueConstraint("favorite_scan_id"),
        schema="museum_sources",
    )
    op.create_index(
        op.f("ix_museum_sources_favorite_scan_scan_id"),
        "favorite_scan",
        ["scan_id"],
        unique=False,
        schema="museum_sources",
    )
    op.create_index(
        op.f("ix_museum_sources_favorite_scan_user_id"),
        "favorite_scan",
        ["user_id"],
        unique=False,
        schema="museum_sources",
    )
    op.create_unique_constraint(
        None, "scan_record", ["scan_id"], schema="museum_sources"
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "scan_record", schema="museum_sources", type_="unique")
    op.drop_index(
        op.f("ix_museum_sources_favorite_scan_user_id"),
        table_name="favorite_scan",
        schema="museum_sources",
    )
    op.drop_index(
        op.f("ix_museum_sources_favorite_scan_scan_id"),
        table_name="favorite_scan",
        schema="museum_sources",
    )
    op.drop_table("favorite_scan", schema="museum_sources")
    # ### end Alembic commands ###
