"""empty message

Revision ID: c05e6f1f0367
Revises: a1b2c3d4e5f6
Create Date: 2026-03-08 21:44:47.265381

"""

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "c05e6f1f0367"
down_revision = "a1b2c3d4e5f6"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        "ix_collection_item_user_id",
        table_name="collection_item",
        schema="museum_sources",
    )
    op.create_index(
        op.f("ix_museum_sources_collection_item_user_id"),
        "collection_item",
        ["user_id"],
        unique=False,
        schema="museum_sources",
    )
    op.create_unique_constraint(
        None, "collection_item", ["id"], schema="museum_sources"
    )
    op.create_unique_constraint(
        None, "user", ["user_id"], schema="museum_sources"
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "user", schema="museum_sources", type_="unique")
    op.drop_constraint(
        None, "collection_item", schema="museum_sources", type_="unique"
    )
    op.drop_index(
        op.f("ix_museum_sources_collection_item_user_id"),
        table_name="collection_item",
        schema="museum_sources",
    )
    op.create_index(
        "ix_collection_item_user_id",
        "collection_item",
        ["user_id"],
        unique=False,
        schema="museum_sources",
    )
    # ### end Alembic commands ###
